# eks-app.yaml
apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app.kubernetes.io/name: eks-app
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: 463470973103.dkr.ecr.ap-northeast-2.amazonaws.com/eks-app:2faaea4eac67d02bf39f722293e05e5ab8971ec5
        ports:
          - protocol: TCP
            containerPort: 8080
