# eks-app.yaml
apiVersion: v1
kind: Service   
metadata:
  name: eks-app-service
spec:
  selector:
    app.kubernetes.io/name: eks-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-app
    spec:
      containers:
      - name: eks-app-container
        image: dockerlecture/eks-app:72551a0db78b15c605fc511b82d0822e5f38151f
        ports:
          - protocol: TCP
            containerPort: 8080
